### ISSUE TITLE
there is a possibility of ignoring the sources

### ISSUE THREAD

**Issue by dougbhz** [SimpleApp/PDFParser#4]
There is a pdf that his font is not found in the catalog.
What to do in these cases

**Comment by SimpleApp** [comment]
So according to the PDF spec, some standard fonts with standard names are supposed to be available "by default" by compliant readers. This library doesn't include them because best practice for modern PDF is to always include the fonts metadata. 

A solution would be to add support for those standard fonts by embedding their metadata in the library. Contributions welcome !
